config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  resources :welcome, only: [:show, :index]
  resources :users, only: [:show, :index, :create, :edit, :update]
  resources :books

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :title, length: { maximum: 200 }
    validates :opinion, presence: true
	validates :opinion, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
 devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
 # deviseでemailを不必要にする
 def email_required?
   false
 end
 def email_changed?
   false
 end


	validates :name, presence: true
	validates :name, uniqueness: true
	validates :name,length: { minimum: 2, maximum: 20 }
	validates :introduction,length: { minimum: 2, maximum: 50 }, on: :update
    attachment :profile_image

    has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
      user_path(current_user.id)
  end

  protected
 	def configure_permitted_parameters
	    added_attrs = [ :name, :email, :password, :password_confirmation ]
	    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
	    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
	    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @user = @book.user_id
    @book = Book.new
    @books = Book.find(params[ :id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
    redirect_to user_path
    end
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
    flash[:notice] = "successfully"
    redirect_to book_path(@book)
    else
      @books = Book.all
      @users = User.all
      @user = current_user
      render :index
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :opinion)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def index
  	@users = User.all
  	@books = Book.all
  	@book = Book.new
  end
  def show
    @book = Book.new
    # if @book.save
    # redirect_to action: 'show'
    # end
  	@user = User.find(params[:id])
    if @user == current_user
    @user = current_user
    end
  	@books = @user.books
  	    #@books = @user.books.page(params[:page]).reverse_order
  end
  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:notice] = "successfully"
    	redirect_to user_path
    end
  end
  def create
    if @user.save
    flash[:notice] = "successfully"
    redirect_to user_path
    else render :edit
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "successfully"
    redirect_to user_path
    else render :edit
    end
  end

  private 
  def user_params
	    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  def set_user
	      @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'users/form', book: @book %>

<%= link_to 'Show', book_path %> |
<%= link_to 'Back', books_path, class: "back" %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
      <div class="row">
        <div class="col-sm-3">
          <%= render 'users/side', user: @user %>
          <%= render 'users/form', book: @book %>
        </div>

<!-- main部分 -->
        <div class="col-sm-9">
          <h1>Books</h1>

          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @books.each do |book| %>
                <tr>

                  <td>
                    <%= attachment_image_tag book.user, :profile_image, :fill, size: "40x40", format: 'jpeg', fallback: 'no_image.jpg', class: "pull-left profile-img" %>
                  </td>
                  <td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
                  <td><%= book.opinion %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <br>


        </div>

      </div>
</div>

app/views/books/new.html.erb
<%= render 'users/form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
      <div class="row">
        <div class="col-sm-3">
           <%= render 'users/side', user: @books.user %>
          <%= render 'users/form', book: @book %>
        </div>

<!-- main部分 -->
        <div class="col-sm-9">
          <h1>Books detail</h1>

          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
                <tr>

                  <td>
                    <%= attachment_image_tag @books.user, :profile_image, :fill, size: "40x40", format: 'jpeg', fallback: 'no_image.jpg', class: "pull-left profile-img" %>
                    <%= link_to @books.user.name, user_path(@books.user) %>
                  </td>
                  <td><%=@books.title %></td>
                  <td><%=@books.opinion %></td>
                  <% if @books.user == current_user %>
                  <td><%= link_to 'Edit', edit_book_path(@books), class: "btn-sm btn-success edit_book_#{@books.id}" %></td>
                  <td><%= link_to 'Destroy',@books, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-danger destroy_book_#{@books.id}" %></td>
                  <% end %>
                </tr>
            </tbody>
          </table>

          <br>


        </div>

      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">
            <font color="white">Bookers</font>
          </a>
        </div>
        
        <div class="collapse navbar-collapse" id="navbarEexample7">
          <ul class="nav navbar-nav navbar-right">
            　<% if user_signed_in? %>
            <li>
              <%= link_to " Home", user_path(current_user.id), class: 'glyphicon glyphicon-home custom home' %></li>
            <li>
              <%= link_to 'User', '/users/', class: 'glyphicon glyphicon-user users' %>
            </li>
            <li>
              <%= link_to " Books", '/books/', class: 'glyphicon glyphicon-book books' %></li>
            <li>
              <%= link_to "logout", destroy_user_session_path, class: 'glyphicon glyphicon-log-out logout', method: :delete  %>
            </li>
            <!-- ここ以下がログアウト -->
             <% else %>
            <li>
             <%= link_to " Home", root_path, class: 'glyphicon glyphicon-home custom home' %>
            </li>
            <li>
             <%= link_to " About", '/welcome/show',class: 'glyphicon glyphicon-link about custom about' %>
            </li>
            <li>
              <%= link_to " sign up", new_user_registration_path,class: 'glyphicon glyphicon-edit sign_up custom sign_up' %>
            </li>
            <li>
              <%= link_to " login", new_user_session_path,class: 'glyphicon glyphicon-log-in sign_in custom sign_in' %>
            </li>
             <% end %>
          </ul>
        </div>
      </div>
    </nav>


    <%= yield %>

    <!-- ここからフッダーー -->
    <footer>
        <div class="col-xs-3 col-xs-offset-8">
        <p class="text-right">CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
   <h2>New Book</h2>
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation col-md-12">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "book_title" %>
  </div>

  <div class="field">
    <%= form.label :opinion %>
    <%= form.text_field :opinion, class: "book_body" %>
  </div>

  <div class="actions">
    <%= form.submit "create book", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_side.html.erb
<!-- ユーザー情報 -->
            <h2>User info</h2>

             <%= attachment_image_tag user, :profile_image, :fill, size: "100x100", format: 'jpeg', fallback: 'no_image.jpg', class: "pull-left profile-img" %>
             <table class="table">
              <tbody><tr></tr> 
              <tr>
                <th>name</th>
                  <td>
                    <%= user.name %>
                  </td>
              </tr>
              <tr>
                <th>introduction</th>
                  <td>
                    <%= user.introduction %>
                  </td>
              </tr>
           </tbody>
          </table>
                <% if current_user.id == user.id %>
            <%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench pull-right edit_user_#{user.id}" %>
                <% end %>
          <br>
<!-- 投稿フォーム -->

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">
          <section class="slice slice-lg sct-color-1">
              <div class="container">
                  <div class="row">
                      <div class="col-md-4 col-md-offset-4">
                          <div class="form-user style-1 rounded has-shadow-1">
                            <div class="form-header text-center">
                                <h2 class="form-header-title">User info</h2>
                            </div>
                            <div class="form-body">
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
                                <%= form_for(@user) do |f| %>
                                    <div class="form-group has-icon">
                                        <label class="control-label" for="inputEmail">Name</label>
                                        <%= f.text_field :name, autofocus: true, class: "form-control name", id:"inputEmail" %>
                                        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                                    </div>
                                      <div class="form-group has-icon">
                                      <label class="control-label" for="inputEmail">Image</label>
                                      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form user_image" %>
                                      </div>
                                        <label class="control-label" for="inputEmail">Introduction</label>
                                        <%= f.text_field :introduction, autofocus: true, class: "form-control introduction", id:"inputEmail" %>
                                    <%= f.submit "Update User", class: "btn btn-lg btn-block btn-default mt-20" %>
                                <% end %>
                            </div>
                          </div> 
                      </div>
                  </div>
              </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
      <div class="row">
        <div class="col-sm-3">
           <%= render 'users/side', user: current_user %>
          <%= render 'users/form', book: @book %>
        </div>

        <div class="col-sm-9">
          <h1>Users</h1>

          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th>image</th>
                <th></th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%= attachment_image_tag user, :profile_image, :fill, size: "40x40", format: 'jpeg', fallback: 'no_image.jpg', class: "pull-left profile-img" %>
                  </td>
                  <td><%= user.profile_image_id %></td>
                  <td><%= user.name %></td>
                  <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <br>


        </div>

      </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
      <div class="row">
        <div class="col-sm-3">
          <%= render 'side', user: @user %>
          <%= render 'form', book: @book %>
        </div>
        <!-- ここから右 -->
        <div class="col-sm-9">
          <h1>Books</h1>

          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @user.books.each do |book| %>
                <tr>

                  <td>
                    <%= attachment_image_tag book.user, :profile_image, :fill, size: "40x40", format: 'jpeg', fallback: 'no_image.jpg', class: "pull-left profile-img" %>
                  </td>
                  <td>
                  	<%= link_to book.title, book_path(book), class: "book_#{book.id}" %>
                  </td>
                  <td>
                  	<%= link_to book.opinion, book_path(book) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <br>


        </div>

      </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
	<div class="row">
	  <div class="col-xs-6 col-xs-offset-3">

		<h1>welcome to<br><span class="glyphicon glyphicon-book books text-center" style="font-size:35px;"></span><strong>Bookers</strong> !!</h1>
		In <span class="glyphicon glyphicon-book books text-center" style="font-size:10px;"></span><strong>Bookers</strong> ,<br>

		you can share and exchange your opinions , inpressions , and emotions<br>

		about varioius books!


		<%= link_to "login", new_user_session_path,class: 'btn btn-info col-xs-10 col-xs-offset-1' %>
		<%= link_to "sign up", new_user_registration_path,class: 'btn btn-success  col-xs-10 col-xs-offset-1' %>
	  </div>



	</div>

</div>

app/views/welcome/show.html.erb
<div class="container">

	<h1>welcome to<span class="glyphicon glyphicon-book books text-center" style="font-size:35px;"></span><strong>Bookers</strong> !!</h1>

</div>